trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_WEBAPP_NAME: 'Nisum'          # The name of your Azure Web App
  AZURE_RESOURCE_GROUP: 'Drupal'   # Your Resource Group
  AZURE_SERVICE_CONNECTION: 'AzureConnection' # Your Service Connection

steps:
  - task: UsePHPVersion@0
    inputs:
      version: '8.3'

  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'drop'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo "Installing Composer dependencies..."
        composer install --no-interaction --prefer-dist --optimize-autoloader

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(AZURE_SERVICE_CONNECTION)
      appName: $(AZURE_WEBAPP_NAME)
      resourceGroupName: $(AZURE_RESOURCE_GROUP)
      package: $(Pipeline.Workspace)/drop
