trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  AZURE_WEBAPP_NAME: 'Nisum'          # The name of your Azure Web App
  AZURE_RESOURCE_GROUP: 'Drupal'      # Your Resource Group
  AZURE_SERVICE_CONNECTION: 'NisumAzureConnection' # Your Service Connection

steps:
  - script: |
      echo "Installing PHP 8.1..."
      sudo apt-get update
      sudo apt-get install -y php8.1 php8.1-cli php8.1-mbstring php8.1-xml
    displayName: 'Install PHP 8.1'

  - script: |
      php --version
    displayName: 'Check PHP Version'

  # Step to install Composer dependencies and create the `drop` directory
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        mkdir -p drop  # Create a directory for the artifact
        echo "Installing Composer dependencies..."
        composer install --no-interaction --prefer-dist --optimize-autoloader
    displayName: 'Install Composer Dependencies'

  # Publish the `drop` artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'drop'  # Path to the artifact directory
      artifact: 'drop'
    displayName: 'Publish Artifact'

  # Download the `drop` artifact in the following steps
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'drop'

  # Deploy to Azure Web App
  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(AZURE_SERVICE_CONNECTION)
      appName: $(AZURE_WEBAPP_NAME)
      resourceGroupName: $(AZURE_RESOURCE_GROUP)
      package: $(Pipeline.Workspace)/drop
